import type { Metadata } from "next";
import { Inter }         from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import { Col, Container, Row } from "react-bootstrap";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title      : "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Container>
                    <Row className={"mb-3"}>
                        <Col>
                            <Link href={"/"}>Főoldal</Link>
                        </Col>
                        <Col>
                            <Link href={"/create"}>Létrehozás</Link>
                        </Col>
                    </Row>
                    {children}
                </Container>
            </body>
        </html>
    );
}
